### PR TITLE
When I need to find just firsts letters of each word

### PR DESCRIPTION
**Pull request by Grigory-Volkov**
Hello!
It will be good upgrade, if you accept this)

Вecause you can do following:
`.search('be', {fields: ['title'], firsts: true})`
And get result: "**Be**line", "Cool **be**sness"
Not this one: "Iz**be**rgamo"

Thanks :)

### CODE REVIEW

**Comment by Gigozzo** [comment]
@brianreavis ?

**Comment by holic** [comment]
Can you add matching tests?

**Comment by Wardrop** [comment]
Came here to suggest the same thing. I've submitted a pull request for a more robust implementation based on word boundaries, rather than whitespace. Includes tests and documentation.

https://github.com/brianreavis/sifter.js/pull/51

**Comment by holic** [comment]
Closing in favor of https://github.com/brianreavis/sifter.js/pull/51

**Pull request closed without merging**
