### PR TITLE
Bump version of csv-parse to ^4.6.3

### LINKED ISSUE #55: Regular expression Denial of Service - ReDoS
The sifter.js uses "csv-parse": "^2.0.0" as dependencies.
The csv-parse.js was affected with Regular expression Denial of Service - ReDoS up to v.4.4.6
[https://www.npmjs.com/advisories/1171](https://www.npmjs.com/advisories/1171)
The actual version csv-parse is v.4.4.7
The suggestion is update csv-parse in sifter.js due found vulnerability.

Versions of csv-parse prior to 4.4.6 are vulnerable to Regular Expression Denial of Service. The __isInt() function contains a malformed regular expression that processes large specially-crafted input very slowly, leading to a Denial of Service. This is triggered when using the cast option.

Remediation
Upgrade to version 4.4.6 or later.

### PR DESCRIPTION
**Pull request by Turbotailz**
Fixes #55

### CODE REVIEW

**Comment by alec-joy** [comment]
@brianreavis Any chance you can take a look at this in the near future?

**Comment by mattgodbolt** [comment]
+1 to taking a look; a number of upstream packages are stuck until this gets merged. Thanks so much!

**Comment by Xenology** [comment]
Would like to see this resolved soon!

**Comment by jessicasalmon** [comment]
+1 to resolving this soon please. Thanks a lot!

**Comment by Xenology** [comment]
@brianreavis Github is pushing automated notifications on all pull requests now for vulnerabilities like this. Any chance we can see this merged?

**Comment by leandrw** [comment]
I've sent a email message and a tweet to @brianreavis remembering him that PRs are already open.
I hope do not bother him 🙃

https://twitter.com/brianreavis

**Comment by brianreavis** [comment]
Hi all – my apologies on the radio silence. For what it’s worth, this reported vulnerability has *no* impact on any project using sifter (e.g. [selectize](https://github.com/selectize/selectize.js)). Further, it doesn’t impact the CLI, as we don’t use the `cast` option. Regardless, that dependency’s now bumped so your scanners should be happier now. It’s updated in 0.5.4 and 0.6.0.

Refs https://github.com/brianreavis/sifter.js/pull/57

**Pull request closed without merging**
